### ISSUE TITLE
linux_install.sh problems

### ISSUE THREAD

**Issue by petesoper** [TriEmbed/edger#16]
1. While researching issue #11 (need instructions for ant/aardvark rebuild) I set up a brand new Ubuntu (vanilla, not minimal) 20.04.6 instance in a virtual machine and ran linux_install.sh with the --install option. I was instructed to log out and back in to get myself into the dialout group and rerun the script. I did that but when the script ran again the instructions were repeated.
 
This problem is caused by the fact that "groups" fails to show the user in dialout, causing the script to redo the steps to add the user to the group. This groups command behavior is described by Linux experts as a feature, not a bug. 
The workaround is to reboot the OS. After being rebooted the "groups" command works as expected. 

2. After the linux_install.sh runs to completion NVM_DIR and related env is not initialized because the code added to $HOME/.bashrc has not sourced. The workaround is to stop and restart the terminal session to gain access to pnpm.
3. After linux_install.sh has finished there are problems with the Desktop icons:
    1. The icon image file is not in $HOME/Pictures
    2. The Desktop/*.desktop files are not executable
    3. When made executable and double clicked the desktop icon file  source is brought up in an editor instead of being executed.
    4. Even after the icon image file is put in place the icons do not appear on the desktop with the specified icon image.
4. The Linux packages python3, wget and libusb-1.0-0 are already installed in Ubuntu Linux 20.04.6 and having linux_install.sh install them might lead to the conclusion it would be safe to remove them: it is completely unsafe to remove any of these three packages because they many critically important packages are dependent on them so removing them sabotages the system. This situation makes it clear that the necessary package list needs to be tailored to specific Linux distros with proper testing. There is a set of required packages for multiple distros documented here: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/get-started/linux-macos-setup.html#get-started-prerequisites . Notice that the first is listed as "Ubuntu and Debian". We probably need more granularity.

**Comment by petesoper** [comment]
1. The linux_install.sh script could use "getent | grep dialout | grep $USER instead of the groups command.
2. The editing of .bashrc could be hoisted so the logout/login step happens afterward. Or, an echo could be added to the end of linux_install.sh to say that to get access to pnpm terminate and restart the terminal session.
3. Desktop issue ideas
    1. A cp can put the desktop icon image file in place.
    2. A chmod can be used to fix the file permissions
    3. This appears to be a "feature" of the Ubuntu Linux I'm working with. Previous builds using an earlier version of 20.04 (20.04.4 from memory) did not behave this way and the "thumbdrive" releases of Linux with the Edger desktop icons worked perfectly fine. The magic trick is this: One must right click on each newly added desktop icon and then left click "Allow launching". How could they get away with changing this between the .4 and .6 release? Now the challenge is to find what "allow launching" does so it can be automatically done by the install process.
    4. Under investigation
4. The script could do a switch on distro (and possibly version) to define the needed package list and define the package manager command.

**Comment by jrhunger** [comment]
in #18 i think i fixed your number 3 above.  At least for gnome.  Possibly those gio commands will fail on kde or something else but then again maybe no equivalent is needed there.
Also in that change i made it say at the end that you have to start a new shell or log out and back in before doing anything.  Should probably just remove the "start a new shell" and make people log out and back in.  Also for dialout i didn't see any dependencies in the script on that so i changed it to not abort in the middle when adding.

**Comment by petesoper** [comment]
This overlaps with #17 and the PR for 17 will close this issue as well.
