### ISSUE TITLE
Ability to install only ant or only aardvark

### ISSUE THREAD

**Issue by jrhunger** [TriEmbed/edger#17]
If someone just wants to run the dev server for Aardvark, they don't need the 3G of esp-idf + .espressif.  Similarly, if someone just wants to update/flash ant, they don't need all the node-JS stuff.  Or people (like me) might want to do both of these things but on different systems.

Proposal, separate scripts ant/linux_install.sh and aardvark/linux_install.sh handling their individual components.  Top-level linux_install.sh still installs everything but does the work by calling the sub-scripts.

**Comment by outoftrun** [comment]
I am working on a way to flash the esp from inside of aardvark, it is on
the list.

Nick

**Comment by jrhunger** [comment]
There will still be a need for initial build/flash, and to re-flash if bricked through aardvark, etc.  Anyway, i am doing this work i just put the issue here to link the PR to.
